compile:
	gcc -o DataGenerator DataGenerator.c
	g++ -o InsertionSort InsertionSort.cc
	g++ -o MergeSort MergeSort.cc
	
run1:
	./DataGenerator 1000
	./InsertionSort 1000
	./MergeSort 1000
	make clean
	
run:
	./DataGenerator 1000
	./InsertionSort	1000
	./MergeSort 1000
	make clean
	./DataGenerator 2000
	./InsertionSort 2000
	./MergeSort 2000
	make clean
	./DataGenerator 10000
	./InsertionSort 10000
	./MergeSort 10000
	make clean
	./DataGenerator 11000
	./InsertionSort 11000
	./MergeSort 11000
	make clean
	./DataGenerator 20000
	./InsertionSort 20000
	./MergeSort 20000
	make clean
	./DataGenerator 30000
	./InsertionSort 30000
	./MergeSort 30000
	make clean
	./DataGenerator 40000
	./InsertionSort 40000
	./MergeSort 40000
	make clean
	./DataGenerator 50000
	./InsertionSort 50000
	./MergeSort 50000
	make clean
	./DataGenerator 60000
	./InsertionSort 60000
	./MergeSort 60000
	make clean
	./DataGenerator 70000
	./InsertionSort 70000
	./MergeSort 70000
	make clean
	./DataGenerator 80000
	./InsertionSort 80000
	./MergeSort 80000
	make clean
	./DataGenerator 90000
	./InsertionSort 90000
	./MergeSort 90000
	make clean
	./DataGenerator 100000
	./InsertionSort 100000
	./MergeSort 100000
	make clean	

clean:
	rm num*.txt

remove:
	rm DataGenerator
	rm InsertionSort
	rm MergeSort
	rm outputMerge.txt
	rm outputInsertion.txt
